### PR TITLE
Bug fixes and Countries added to dropdown

### LINKED ISSUE #122: Tajikistan is missing in the list of countries
Image

### PR DESCRIPTION
**Pull request by mrkhan**
Bug fixes and Countries added to dropdown
resolves #122 and #124

### CODE REVIEW

File: src/app/dashboard/dashboard.component.ts [hunk 1]
```diff
@@ -83,12 +83,12 @@ export class DashboardComponent implements OnInit {
             if (queryParams['topics'] == null)
                 queryParams.topics = ''
 
-            this.dataService.updateURL(queryParams)
+            // this.dataService.updateURL(queryParams)
```
Comment (ElJocho) [inline src/app/dashboard/dashboard.component.ts:86]: why is this commented out now?

File: src/app/data.service.ts [hunk 2]
```diff
@@ -64,27 +63,27 @@ export class DataService {
...
+                    //     interval: queryParams && queryParams.interval ? queryParams.interval : this.defaultIntervalValue,
+                    //     start: queryParams && queryParams.start ? queryParams.start : queryParams && queryParams.hashtag ? meta.result.min_timestamp : tempStart,
+                    //     end: queryParams && queryParams.end ? queryParams.end : this.maxDate,
+                    //     countries: queryParams && queryParams.countries ? queryParams.countries : '',
+                    //     topics: queryParams && queryParams.topics ? queryParams.topics : ''
+                    // }
+                    // if (queryParams?.fit_to_content !== undefined) {
+                    //     defaults.fit_to_content = queryParams.fit_to_content
+                    // }
+                    // this.updateURL(defaults)
```
Comment (ElJocho) [inline src/app/data.service.ts:86]: same question here, if it does not break anything, we can just remove it right? But are you sure it is unneeded?

File: src/assets/static/json/countryCodes.json [hunk 3]
```diff
@@ -841,7 +857,7 @@
   },
   {
     "name": "Kosovo",
-    "value": "XKX"
+    "value": "XK"
```
Comment (ElJocho) [inline src/assets/static/json/countryCodes.json:860]: I thought we used the three letter country codes in our db, why only two letters for cosovo?

Comment (mrkhan) [reply src/assets/static/json/countryCodes.json:860]: Benni told that for the new data we'll have "XK" for Kosovo. Although in current db we have "XKX" for Kosovo.

Comment (ElJocho) [reply src/assets/static/json/countryCodes.json:860]: and plotly just happily takes 2 letter country codes? Then we would be good to go

**Comment by ElJocho** [comment]
https://github.com/GIScience/ohsome-now-stats-frontend/issues/126

**Review by ElJocho — APPROVED** [review]
